global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Alertmanager could be added here in future

rule_files:
  # Alerting rules could be added here in future

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: metrics-server
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8080']